Update README.md

diff --git a/bin/X11/WM/dynamic_theme b/bin/X11/WM/dynamic_theme
--- a/bin/X11/WM/dynamic_theme
+++ b/bin/X11/WM/dynamic_theme
@@ -1,37 +1,50 @@
 #!/bin/sh
 set -e
-# work on this : colors not 100% accurete
+
 . "$__distro_path_lib"
 . "${__distro_path_root}/lib/common/WM"
+. "${__distro_path_root}/lib/common/openbox"
+
 . "${Distro_config_file}"
 
-_style="dynamic"
 dynamicGTKPATH="$HOME/.local/dynamic_theme"
 CONFIGPATH="$HOME/.config"
 
 wallpaper="${1:-}"
 
-if [ -z "${wallpaper}" ];then
-	if [ -t 1 ];then # on terminal
-		pickbg
+if [ "$Style_name" != "dynamic" ];then
+	current_mode_are="dynamic"
+else
+	old_wallpaper_are="$wallpaper_are"
+	if [ -z "${wallpaper}" ];then
+		if [ -t 1 ];then # on terminal
+			pickbg save
+		else
+			popup_terminal "pickbg save"
+		fi
+	elif [ -n "${wallpaper}" ];then
+		setbg -s "$(realpath "${wallpaper}")"
+	fi
+	
+	. "${Distro_config_file}"
+	
+	if [ "$wallpaper_are" = "$old_wallpaper_are" ];then
+		current_mode_are="modified"
 	else
-		popup_terminal pickbg
+		current_mode_are="generate"
 	fi
 fi
 
-if [ -z "${wallpaper}" ];then
-	wallpaper="${wallpaper_are}"
-else
-	wallpaper="$(realpath "${wallpaper}")"
-	setbg -s "${wallpaper}"
-fi
+_style="dynamic"
+dynamic_theme_scripts_dir="${__distro_path_root}/lib/Dynamic"
+temp_theme_file_dir="/tmp/$USER/theme_color_builder_output"
+themes_builder_output_dir="${temp_theme_file_dir}/templates"
 
-dynamic_theme_scripts_dir="${__distro_path_root}/bin/dynamic_theme_scripts"
-dynamic_theme_common_file_name="common.sh"
-dynamic_theme_sed_them_file_name="sed_them.sh"
-dynamic_theme_common_file_path="${dynamic_theme_scripts_dir}/${dynamic_theme_common_file_name}"
-. "${dynamic_theme_common_file_path}"
-
+show_em(){
+	echo "[ERROR] $0 ${sourced_file}: $1"
+	exit 1
+}
+	
 # Remove temp theme file directory if it exists
 if [ -d "$temp_theme_file_dir" ];then
 	rm -rdf "$temp_theme_file_dir"
@@ -39,90 +52,33 @@ fi
 
 mkdir -p "$temp_theme_file_dir"
 
-"${dynamic_theme_scripts_dir}"/theme_color_file_builder "${dynamic_theme_scripts_dir}" "$dynamic_theme_common_file_name" "${wallpaper}" || show_em "failed to run theme_color_file_builder"
-"${dynamic_theme_scripts_dir}"/themes_builder "${dynamic_theme_scripts_dir}" "$dynamic_theme_common_file_name" "${dynamic_theme_sed_them_file_name}" || show_em "failed to run themes_builder"
-
-cp -r "${themes_builder_output_dir}/colors-dunstrc.conf" "$CONFIGPATH/dunst/theme.dunstrc"
-[ ! -f "$HOME/.config/dunst/global" ] && cp -r "${__distro_path_root}/skel_extra/.config/dunst/global" "$HOME/.config/dunst" || :
-[ ! -f "$HOME/.config/dunst/experimental" ] && cp -r "${__distro_path_root}/skel_extra/.config/dunst/experimental" "$HOME/.config/dunst" || :
-[ ! -f "$HOME/.config/dunst/theme.dunstrc" ] && cp -r "${__distro_path_root}/skel_extra/.config/dunst/theme.dunstrc" "$HOME/.config/dunst" || :
-cat "$CONFIGPATH"/dunst/global "$CONFIGPATH"/dunst/theme.dunstrc > "$CONFIGPATH"/dunst/dunstrc
-
-dunstify -u normal --replace=699 -i "${__distro_path_all_distro_themes}/icons/channelmixer.svg" "Applying Style : ${_style}"
-
-if [ "$_panel_name_" = 'polybar' ];then
-	cp -r "${themes_builder_output_dir}/colors-polybar.conf" "${CONFIGPATH}/polybar/${_style}/colors.ini"
-elif [ "$_panel_name_" = 'tint2' ];then
-	echo "/.config/tint2/${_style}_new.tint2rc" > "${CONFIGPATH}/tint2/tint2-sessionfile"
-	cp -r "${themes_builder_output_dir}/colors-tint2rc.conf" "${CONFIGPATH}/tint2/${_style}_new.tint2rc"
-	sed -i "s/(((__distro_path_root)))/${__distro_path_root}/g" "${CONFIGPATH}/tint2/${_style}_new.tint2rc"
-	sed -i "s|greeter_background=.*|greeter_background=\"${wallpaper}\"|g" "${CONFIGPATH}/blob/${_style}/lightdm-gtk-greeter.conf"
+gtk_theme_path="$HOME/.themes"
+gtk_icon_path="$HOME/.icons"
+	
+if [ "$current_mode_are" = "dynamic" ];then
+	if [ ! -f "$HOME/.config/blob/${_panel_name_}/${_style}/style.conf" ];then
+		mkdir -p "$HOME/.config/blob/${_panel_name_}/${_style}"
+		cp -r "${__distro_path_root}/blob/${_panel_name_}/${_style}/style.conf" "$HOME/.config/blob/${_panel_name_}/${_style}"
+	fi
+	dunstify -u normal --replace=699 -i "${__distro_path_all_distro_themes}/icons/channelmixer.svg" "Applying Style : ${_style}"
+elif [ "$current_mode_are" = "generate" ];then
+	sourced_file="at theme_color_file_builder"
+	. "${dynamic_theme_scripts_dir}/theme_color_file_builder"
 fi
 
-if [ -d "${CONFIGPATH}/jgmenu" ];then
-	. "${themes_builder_output_dir}/colors-jgmenu.conf"
-	jgmenurc_file="${CONFIGPATH}/jgmenu/jgmenurc"
-	sed -i "s/font .*/font                = $font $size/g" "$jgmenurc_file"
-	sed -i "s/color_menu_bg .*/color_menu_bg       = $color_menu_bg/g" "$jgmenurc_file"
-	sed -i "s/color_menu_border .*/color_menu_border   = $color_menu_border/g" "$jgmenurc_file"
-	sed -i "s/color_norm_bg .*/color_norm_bg       = $color_norm_bg/g" "$jgmenurc_file"
-	sed -i "s/color_norm_fg .*/color_norm_fg       = $color_norm_fg/g" "$jgmenurc_file"
-	sed -i "s/color_sel_bg .*/color_sel_bg        = $color_sel_bg/g" "$jgmenurc_file"
-	sed -i "s/color_sel_fg .*/color_sel_fg        = $color_sel_fg/g" "$jgmenurc_file"
-	sed -i "s/color_sel_border .*/color_sel_border    = $color_sel_border/g" "$jgmenurc_file"
-	sed -i "s/color_title_bg .*/color_title_bg      = $color_title_bg/g" "$jgmenurc_file"
-	sed -i "s/color_title_fg .*/color_title_fg      = $color_title_fg/g" "$jgmenurc_file"
-	sed -i "s/color_title_border .*/color_title_border  = $color_title_border/g" "$jgmenurc_file"
-	sed -i "s/color_sep_fg .*/color_sep_fg        = $color_sep_fg/g" "$jgmenurc_file"
-	sed -i "s/stay_alive .*/stay_alive        = $stay_alive/g" "$jgmenurc_file"
-	sed -i "s/menu_padding_right .*/menu_padding_right        = $menu_padding_right/g" "$jgmenurc_file"
-	sed -i "s/menu_padding_bottom .*/menu_padding_bottom        = $menu_padding_bottom/g" "$jgmenurc_file"
-	sed -i "s/menu_padding_left .*/menu_padding_left        = $menu_padding_left/g" "$jgmenurc_file"
-	sed -i "s/menu_radius .*/menu_radius        = $menu_radius/g" "$jgmenurc_file"
-	sed -i "s/sep_halign .*/sep_halign        = $sep_halign/g" "$jgmenurc_file"
-	sed -i "s/icon_size .*/icon_size        = $icon_size/g" "$jgmenurc_file"
-	sed -i "s/icon_theme .*/icon_theme        = $icon_theme/g" "$jgmenurc_file"
-	sed -i "s/menu_border .*/menu_border        = $menu_border/g" "$jgmenurc_file"
-fi
+. "$HOME/.config/blob/${_panel_name_}/${_style}/style.conf"
+	
+sourced_file="at style_file_builder"
+. "${__distro_path_root}"/lib/Style/style_file_builder
+sourced_file="at style_setter"
+. "${__distro_path_root}"/lib/Style/style_setter
 
-if [ -d "${CONFIGPATH}/geany" ];then
-	geany_theme_path="${CONFIGPATH}/geany"
-	echo "${_style}_new.conf" > "${geany_theme_path}/theme.conf"
-	cp -r "${themes_builder_output_dir}/colors-geany.conf" "$geany_theme_path/colorschemes/${_style}_new.conf"
-fi
+setbg -r || show_em "failed to run setbg -r"
 
-if [ -d "${CONFIGPATH}/kitty" ];then
-	kitty_theme_path="${CONFIGPATH}/kitty"
-	mkdir -p "$kitty_theme_path/themes"
-	echo "background_opacity 0.8" > "${kitty_theme_path}/theme.conf"
-	echo "# color scheme" >> "${kitty_theme_path}/theme.conf"
-	echo "include ./themes/${_style}_new.conf" >> "${kitty_theme_path}/theme.conf"
-	cp -r "${themes_builder_output_dir}/colors-kitty.conf" "$kitty_theme_path/themes/${_style}_new.conf"
-fi
+sourced_file="at gtk_theme_builder"
+. "${dynamic_theme_scripts_dir}/gtk_theme_builder"
+sourced_file="at themes_builder"
+. "${dynamic_theme_scripts_dir}/themes_builder"
+sourced_file=""
 
-if [ -d "${CONFIGPATH}/alacritty" ];then
-	alacritty_theme_path="${CONFIGPATH}/alacritty"
-	mkdir -p "$alacritty_theme_path/colorschemes"
-	cp -r "${themes_builder_output_dir}/colors-alacritty.yml" "$alacritty_theme_path/colorschemes/${_style}_new.yml"
-	( cd "$alacritty_theme_path" && ln -sf "colorschemes/${_style}_new.yml" "colors.yml" )
-fi
-
-if [ -d "${CONFIGPATH}/rofi" ];then
-	cp -r "${themes_builder_output_dir}/colors-rofi.rasi" "${CONFIGPATH}/rofi/theme.rasi"
-fi
-
-if [ -d "${CONFIGPATH}/x11/Xresources.d" ];then
-	cp -r "${themes_builder_output_dir}/colors.Xresources" "${CONFIGPATH}/x11/Xresources.d/themes/${_style}_new"
-	( cd "${CONFIGPATH}/x11/Xresources.d" && ln -sf "themes/${_style}_new" "colors" )
-fi
-
-if [ -d "${CONFIGPATH}/bspwm" ];then
-	cp -r "${themes_builder_output_dir}/colors-dunstrc.conf" "${CONFIGPATH}/bspwm/theme.conf"
-fi
-
-if pgrep openbox >/dev/null 2>&1;then
-	reconfigure-openbox || show_em "failed to run reconfigure-openbox "
-fi
-
-"${dynamic_theme_scripts_dir}"/gtk_theme_builder "${dynamic_theme_scripts_dir}" "$dynamic_theme_common_file_name" "${dynamic_theme_sed_them_file_name}" || show_em "failed to run gtk_theme_builder"
 "${__distro_path_root}"/bin/X11/WM/panel_launcher || show_em "failed to run panel_launcher"
diff --git a/bin/X11/WM/pre_launch_wm b/bin/X11/WM/pre_launch_wm
--- a/bin/X11/WM/pre_launch_wm
+++ b/bin/X11/WM/pre_launch_wm
@@ -1,6 +1,8 @@
 #!/bin/sh
+
 . "$__distro_path_lib"
 . "${__distro_path_root}/lib/common/WM"
+. "${__distro_path_root}/lib/common/openbox"
 
 mc-session start
 mc-session db &
@@ -11,10 +13,18 @@ else
 	echo "$0: ERROR failed to mkdir /tmp/$USER"
 fi
 
-if [ ! -f "${WM_config_dir}/menu_picked" ];then	
-	_picked_panel_="$("${__distro_path_root}"/bin/X11/WM/panel_picker)"
-	"${__distro_path_root}"/bin/X11/WM/style_file_builder "${_picked_panel_}"
-	"${__distro_path_root}"/bin/X11/WM/style_setter "$_picked_panel_"
+if [ ! -f "${WM_config_dir}/menu_picked" ];then
+	show_em(){
+		echo "[ERROR] $0 ${sourced_file}: $1"
+		exit 1
+	}
+	_style="default"
+	_panel_name_="$("${__distro_path_root}"/bin/X11/WM/panel_picker)"
+	sourced_file="at style_file_builder"
+	. "${__distro_path_root}"/lib/Style/style_file_builder
+	sourced_file="at style_setter"
+	. "${__distro_path_root}"/lib/Style/style_setter
+	sourced_file=""
 	touch "${WM_config_dir}/menu_picked"
 fi
 
diff --git a/bin/X11/WM/style_changer b/bin/X11/WM/style_changer
--- a/bin/X11/WM/style_changer
+++ b/bin/X11/WM/style_changer
@@ -2,24 +2,33 @@
 set -e
 . "$__distro_path_lib"
 . "${__distro_path_root}/lib/common/WM"
+. "${__distro_path_root}/lib/common/openbox"
 
 _panel_name_="${1:-}"
-style="${2:-}"
+_style="${2:-}"
 no_notify="${3:-false}"
 
-"${__distro_path_root}"/bin/X11/WM/style_file_builder "${_panel_name_}" "${style}"
-"${__distro_path_root}"/bin/X11/WM/style_setter "${_panel_name_}" "${style}"
+show_em(){
+	echo "[ERROR] $0 ${sourced_file}: $1"
+	exit 1
+}
+
+sourced_file="at style_file_builder"
+. "${__distro_path_root}"/lib/Style/style_file_builder
+sourced_file="at style_setter"
+. "${__distro_path_root}"/lib/Style/style_setter
+sourced_file=""
 
 . "${Distro_config_file}"
 
 if [ "$random_wallpaper" = true ];then
-	setbg --random "${style}" || show_em "failed to run setbg -d ${style}"
+	setbg --random "${_style}" || show_em "failed to run setbg -d ${_style}"
 else
-	setbg -r "${style}" || show_em "failed to run setbg -r"
+	setbg -r || show_em "failed to run setbg -r"
 fi
 
 "${__distro_path_root}"/bin/X11/WM/panel_launcher
 
 if [ "$no_notify" = false ];then
-	dunstify -u normal --replace=699 -i "${__distro_path_all_distro_themes}/icons/channelmixer.svg" "Applying Style : ${style}"
+	dunstify -u normal --replace=699 -i "${__distro_path_all_distro_themes}/icons/channelmixer.svg" "Applying Style : ${_style}"
 fi
