Update README.md

diff --git a/lib/common/Package-manager b/lib/common/Package-manager
--- a/lib/common/Package-manager
+++ b/lib/common/Package-manager
@@ -1,3 +1,32 @@
+########################################################################
+# Check the connection by downloading a file from ftp.debian.org. No disk space used.
+# Usage: connectiontest [attempts]
+# If attempt count is not specified or 0, then it will loop forever and exit(!) your main program with 1 exit status.
+connectiontest() {
+    local TEXT_CHECKING='Checking internet connection...'
+    local TEXT_FAILED='Internet connection test failed!'
+    local TEXT_ASK_RETRY=$'\n\nThis script requires a working internet connection. Please configure your internet connection, then hit "Enter" to continue, else hit "q" to quit.'
+    local TEXT_ABORT='Script aborted.'
+    local TEXT_OK='Internet connection test passed!'
+
+    local -i i attempts=${1-0}
+    for (( i=0; i < attempts || attempts == 0; i++ )); do
+        say "$TEXT_CHECKING"
+        if wget -O - 'http://ftp.debian.org/debian/README' &> /dev/null; then
+            say "$TEXT_OK" 1
+            return 0
+        fi
+        say "$TEXT_FAILED"
+        if (( i == attempts - 1 )); then # if last attempt
+            return 1
+        elif prompt "$TEXT_ASK_RETRY" Q; then # if user wants to quit
+            say "$TEXT_ABORT" 2
+            (( attempts == 0 )) && exit 1 || return 1
+        fi
+        tput clear
+    done
+}
+
 # Usage: say text [delayAfterText|pause]
 say() {
     local width=$(tput cols 2>/dev/tty)
