Update README.md

diff --git a/bin/apps/my-mpv b/bin/apps/my-mpv
--- a/bin/apps/my-mpv
+++ b/bin/apps/my-mpv
@@ -5,7 +5,7 @@
 MPV_PROFILE=bl-pseudo-gui
 
 if ! hash mpv; then
-    echo "$0: mpv binary is missing. Please issue 'sudo apt-get install mpv'." >&2
+    echo "$0: mpv binary is missing. Please issue 'my-superuser apt-get install mpv'." >&2
     exit 1
 fi
 
diff --git a/bin/not_add_2_path/apps_center/distrobox b/bin/not_add_2_path/apps_center/distrobox
--- a/bin/not_add_2_path/apps_center/distrobox
+++ b/bin/not_add_2_path/apps_center/distrobox
@@ -9,40 +9,51 @@ app_name=$(basename $0)
 skip_test="{1-}"
 
 if command -v $app_name 2>/dev/null && dpkg -s $app_name &>/dev/null;then
-	sudo touch '/usr/share/my_stuff/system_files/Distrobox_ready'
+	my-superuser touch '/usr/share/my_stuff/system_files/Distrobox_ready'
 	exit
 fi
 
 ###################################################################
 
 . "/usr/share/my_stuff/system_files/Package-manager"
-clear
-say
-say "INSTALL ${app_name}."
-say '------------------------'
-say "This script will install ${app_name}."
-say
-if [[ -z "${skip_test}" ]];then
-	clear
-	connectiontest 1 || failed_to_run "failed to install no internet."
+while true; do # do it until the package is successfully installed or user wants to exit
+	if [[ $TRYAGAIN ]]; then # previous try failed
+		say
+		say "There was a problem installing ${app_name}."
+		say
+		prompt '  Hit any key to try again, or "q" to quit...' Q && break
+	fi
+	TRYAGAIN=true
 	
 	clear
-	say 'Updating sources...' 1
-	Package_update_ || failed_to_run "failed to update repo."
+	say
+	say "INSTALL ${app_name}."
+	say '------------------------'
+	say "This script will install ${app_name}."
+	say
+	if [[ -z "${skip_test}" ]];then
+		clear
+		connectiontest 1 || failed_to_run "failed to install no internet."
+		
+		clear
+		say 'Updating sources...' 1
+		Package_update_ || failed_to_run "failed to update repo."
+		
+		clear
+	fi
 	
-	clear
-fi
-
-say 'Installing package...' 1
-Package_installer_ ${app_name} || failed_to_run "failed to install ${app_name}"
-
-sudo ln -sf /usr/share/my_stuff/bin/not_add_2_path/DistroGUI/distrogui.desktop /usr/share/applications
-sudo ln -sf /usr/share/my_stuff/bin/not_add_2_path/DistroGUI/distrogui /usr/share/my_stuff/system_files/bin
-
-sudo touch '/usr/share/my_stuff/system_files/Distrobox_ready'
-
-say
-say "${app_name} has been installed successfully."
-say
-
-
+	say 'Installing package...' 1
+	Package_installer_ ${app_name} || failed_to_run "failed to install ${app_name}"
+	
+	my-superuser ln -sf /usr/share/my_stuff/bin/not_add_2_path/DistroGUI/distrogui.desktop /usr/share/applications
+	my-superuser ln -sf /usr/share/my_stuff/bin/not_add_2_path/DistroGUI/distrogui /usr/share/my_stuff/system_files/bin
+	
+	my-superuser touch '/usr/share/my_stuff/system_files/Distrobox_ready'
+	
+	say
+	say "${app_name} has been installed successfully."
+	say
+	[[ -z "${skip_test}" ]] && say 'Hit any key to exit...'
+	[[ -z "${skip_test}" ]] && read -srn1
+	break
+done	
