Update README.md

diff --git a/bin/apps/sleep_until b/bin/apps/sleep_until
--- a/bin/apps/sleep_until
+++ b/bin/apps/sleep_until
@@ -1,41 +1,47 @@
 #!/bin/sh
 # if this line exist script will be part of hub script.
 
-# Sleep_Until.sh - YAD GUI for RTCWake: Make your computer sleep and wake up at a given time
-# Copyright (C) 2016 Jorge A. Duarte - babetoduarte@gmail.com
+#######################################################################
+# This script uses YAD to create a GUI for setting sleep time using rtcwake.
+# Make sure the hardware clock is set to UTC or modify the rtcwake call accordingly.
+#######################################################################
+check_4_dependencies_if_installed yad rtcwake || exit 1
 
-# This program is free software; you can redistribute it and/or
-# modify it under the terms of the GNU General Public License
-# as published by the Free Software Foundation; either version 2
-# of the License, or (at your option) any later version.
-
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-
-# You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
-
-#######################################################################33
-# SleepUntil is a bash script, which makes use of [YAD](https://code.google.com/archive/p/yad/) to capture data for *rtcwake* through a GUI Dialog. Through *rtcwake* the OS sleeps, and wakes up at a given time (today or tomorrow).
-
-#### Hardware Clock:
-# Hardware clock must be set to UTC. If not, the script must be edited (remove the -u flag from rtcwake):
-# replace "my-superuser rtcwake -m mem -u -t $(date +%s -d "$foo")" for:
-# my-superuser rtcwake -m mem -t $(date +%s -d "$foo")
-
-# Input parameters on GUI:
-#    - Day: ['today' / 'tomorrow']
-#    - Time: [Time in 24h format (i.e. 06:30 or 22:15)]
-#######################################################################33
-
+# Input parameters on GUI
 frmdata=$(yad --title "Sleep Until" --form --field "Today / Tomorrow" --field="Time (24h format)")
 
+# Extract day and time
 frmday=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $1 }')
 frmtime=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $2 }')
 
+# Basic validation for "day" and "time"
+if [ "$frmday" != "today" ] && [ "$frmday" != "tomorrow" ];then
+    yad --error --title="Invalid Day" --text="Error: Invalid day selected. Please choose 'today' or 'tomorrow'."
+    exit 1
+fi
+
+if echo "$frmtime" | grep -qE '^([01][0-9]|2[0-3]):([0-5][0-9])$'; then
+    yad --error --title="Invalid Time" --text="Error: Invalid time format. Please enter time in 24-hour format (HH:MM)."
+    exit 1
+fi
+
 foo="$frmday $frmtime"
 
-my-superuser rtcwake -m mem -u -t $(date +%s -d "$foo")
+if ! date -d "$foo" >/dev/null 2>&1; then
+    yad --error --title="Invalid Date" --text="Error: Invalid date or time. Please check the entered values."
+    exit 1
+fi
+
+timestamp=$(date +%s -d "$foo")
+current_timestamp=$(date +%s)
+if [ "$timestamp" -le "$current_timestamp" ]; then
+    yad --error --title="Invalid Time" --text="Error: The selected time is in the past. Please choose a future time."
+    exit 1
+fi
+
+apps_as_root "rtcwake -m mem -u -t \"$timestamp\"" || {
+    yad --error --title="Error" --text="Error: rtcwake failed. Please check the command or system logs for more details."
+    exit 1
+}
+
+yad --info --title="Success" --text="System will sleep now and wake up at the specified time."
diff --git a/bin/bin/check_4_dependencies_if_installed b/bin/bin/check_4_dependencies_if_installed
--- a/bin/bin/check_4_dependencies_if_installed
+++ b/bin/bin/check_4_dependencies_if_installed
@@ -4,25 +4,9 @@ not_installed_apps_are=""
 . "/usr/share/my_stuff/system_files/Package-manager"
 
 on_terminal(){
-	_on_terminal=true
-	_STDOUT=""
-	_STDERR=""
-	
-   	if [ -t 0 ];then
-   		if [ ! -t 1 ];then
-   			_STDOUT="STDOUT"
-   			_on_terminal=false
-   		fi
-   		if [ ! -t 2 ];then
-   			_STDERR="STDERR"
-   			_on_terminal=false
-   		fi
-       	if [ "$_on_terminal" = false ];then
-       		echo "$0: STDIN is on terminal, but not ${STDOUT} , ${_STDERR}" >&2
-           	return 1
-       	fi
+	if [ ! -t 1 ];then
+   		return 1
    	fi
-   	return 0
 }
 
 has() {
@@ -31,9 +15,9 @@ has() {
 	esac
 }
 
-	# print error message
+# print error message
 _pem() {
-	>&2 printf '\033[31;1merror :\033[m %s\n' "$1"
+	>&2 printf '\033[31;1merror :\033[m %s\n' "$1" && return 1
 }
 
 Do_want_to_install_dependencies()
@@ -42,9 +26,9 @@ Do_want_to_install_dependencies()
 	read -r yn
 	yn="$(echo "$yn" | tr '[:upper:]' '[:lower:]')"
 	case $yn in 
-		y*) Package_installer_ ${not_installed_apps_are};;
-		n*) echo "exiting..." && exit;;
-		* ) _pem "invalid response" ;;
+		y*) Package_installer_ ${not_installed_apps_are} || _pem "Failed to run Package_installer_";;
+		n*) _pem "exiting...";;
+		* ) _pem "invalid response";;
 	esac
 }
 	
@@ -55,13 +39,13 @@ done
 if [ -n "${dependencies_not_installed}" ];then
 	if on_terminal;then
 			_pem "Missing dependencies, please install: ${dependencies_not_installed%??}."
-			Do_want_to_install_dependencies
+			Do_want_to_install_dependencies || return 1
 	else
 		yad --image="dialog-question" \
 			--title "Alert" \
 			--text-align=center \
 			--text="Missing dependencies, please install" \
 			--entry --entry-label=Label \
-			--entry-text="${not_installed_apps_are}"
+			--entry-text="${not_installed_apps_are}" && return 1
 	fi
 fi
