Update README.md

diff --git a/bin/my_installer/chroots_center/torproxy b/bin/my_installer/chroots_center/torproxy
--- a/bin/my_installer/chroots_center/torproxy
+++ b/bin/my_installer/chroots_center/torproxy
@@ -249,6 +249,7 @@ my-superuser chmod +x "$CHROOT_SCRIPT_PATH/$start_tor_chroot_script_name" || fai
 say "Create ${start_torproxy_script_name} for controlling chroot..."
 echo '#!/bin/sh' | my-superuser tee "$CHROOT_SCRIPT_PATH/$start_torproxy_script_name" > /dev/null
 echo "set -e
+__arg_=\"\${1-}\"
 
 if dpkg -s ufw >/dev/null 2>&1;then
 	ignore_ufw=false
@@ -283,8 +284,11 @@ start_tor(){
 	else
 		stop_ufw
 		# Only save the rules when we are sure that everything is working
-		iptables-save >$RULES
-	
+		if ! iptables-save | tee \"$RULES\" >/dev/null 2>&1;then
+			echo \"failed to create $RULES existing.\"
+		fi
+		chmod 700 \"$RULES\"
+		
 		### flush iptables
 		iptables -F
 		iptables -t nat -F
@@ -317,16 +321,20 @@ stop_tor(){
 	if test -f \"$RULES\"; then
 		echo \"Restoring previous rules from $RULES\"
 		iptables -F
-		iptables-restore <\"$RULES\"
-		rm \"$RULES\"
-		start_ufw
+		iptables -t nat -F
+		iptables -t mangle -F
+		iptables -X
+		iptables -t nat -X
+		iptables -t mangle -X
+		if iptables-restore < \"$RULES\";then
+			rm \"$RULES\"
+			start_ufw
+		fi
 	else
 		echo \"$RULES does not exist. Not doing anything.\"
 		exit
 	fi
 }
-
-__arg_=\"\${1-}\"
 
 case \"\$__arg_\" in
 start)
