Update README.md

diff --git a/bin/must_create_script/xsessions/main b/bin/must_create_script/xsessions/main
--- a/bin/must_create_script/xsessions/main
+++ b/bin/must_create_script/xsessions/main
@@ -4,7 +4,7 @@ usr_locl_share_dir="$HOME/.local/share"
 usr_setup_flag_file="$usr_locl_share_dir/usr-flag-setup"
 usr_xsessionrc="$HOME/.xsessionrc"
 usr_resources="$HOME/.config/x11/xresources"
-global_usr_xsessionrc="/usr/share/my_stuff/lib/xsessionrc/xsessionrc"
+xsessions_lib_path="/usr/share/my_stuff/lib/xsessions"
 
 if [ -d "/usr/share/my_stuff/system_files/bin" ];then
 	PATH="/usr/share/my_stuff/system_files/bin:$PATH"
@@ -14,22 +14,13 @@ fi
 
 # This section is only executed on first boot.
 if [ ! -f "$usr_setup_flag_file" ];then
-	if [ -f "$global_usr_xsessionrc" ];then
-		. "$global_usr_xsessionrc" 
-	else
-		echo "$0: cannot source $global_usr_xsessionrc" >&2
-	fi
-	
     # Import user config files
-    if [ -x /usr/share/my_stuff/bin/not_add_2_path/skel_user_setup_ ];then
-        /usr/share/my_stuff/bin/not_add_2_path/skel_user_setup_ "$usr_setup_flag_file" || failed_to_run_skel_user_setup_=true
+    if [ -x "${xsessions_lib_path}"/skel_user_setup_ ];then
+        if "${xsessions_lib_path}"/skel_user_setup_ "$usr_setup_flag_file";then
+        	"${xsessions_lib_path}"/skel_user_setup_ "$usr_setup_flag_file" || echo "failed to run skel_user_setup_"
+        fi
     fi
-    
-    if [ "$failed_to_run_skel_user_setup_" = true ]
-	then
-		/usr/share/my_stuff/bin/not_add_2_path/skel_user_setup_ "$usr_setup_flag_file" || echo "failed to run skel_user_setup_"
-	fi
-	
+
     # Actions here are usually handled by scripts in /etc/X11/Xsession.d/
     # but on first boot, user config files were not yet imported at that point.
     # This makes a difference to the live session, unless user logs out/in.
@@ -53,33 +44,33 @@ if [ ! -f "$usr_setup_flag_file" ];then
 fi
 
 case $SHELL in
-  */bash)
-    [ -z "$BASH" ] && exec $SHELL $0 "$@"
-	. ${HOME}/.config/myshell/profile.sh
-	. ${HOME}/.config/myshell/bash/bprofile.sh
-    ;;
-*/zsh)
-    . ${HOME}/.config/myshell/profile.sh
-    . ${HOME}/.config/myshell/zsh/zprofile.sh
-    ;;
-  */csh|*/tcsh)
-    # [t]cshrc is always sourced automatically.
-    # Note that sourcing csh.login after .cshrc is non-standard.
-    xsess_tmp=$(mktemp /tmp/${HOME}/xsess-env-XXXXXX)
-    $SHELL -c "if (-f /etc/csh.login) source /etc/csh.login; if (-f ~/.login) so                                                                                                                                                                                 urce ~/.login; /bin/sh -c 'export -p' >! $xsess_tmp"
-    . $xsess_tmp
-    rm -f $xsess_tmp
-    ;;
-  */fish)
-    . ${HOME}/.config/myshell/profile.sh
-	. ${HOME}/.config/myshell/bash/bprofile.sh
-    xsess_tmp=$(mktemp /tmp/${HOME}/xsess-env-XXXXXX)
-    $SHELL --login -c "/bin/sh -c 'export -p' > $xsess_tmp"
-    . $xsess_tmp
-    rm -f $xsess_tmp
-    ;;
-  *) # Plain sh, ksh, and anything we do not know.
-    . ${HOME}/.config/myshell/profile.sh
-	. ${HOME}/.config/myshell/bash/bprofile.sh
-    ;;
+	*/bash)
+    	[ -z "$BASH" ] && exec $SHELL $0 "$@"
+		. ${HOME}/.config/myshell/profile.sh
+		. ${HOME}/.config/myshell/bash/bprofile.sh
+	;;
+	*/zsh)
+    	. ${HOME}/.config/myshell/profile.sh
+    	. ${HOME}/.config/myshell/zsh/zprofile.sh
+	;;
+	*/csh|*/tcsh)
+    	# [t]cshrc is always sourced automatically.
+    	# Note that sourcing csh.login after .cshrc is non-standard.
+    	xsess_tmp=$(mktemp /tmp/${HOME}/xsess-env-XXXXXX)
+    	$SHELL -c "if (-f /etc/csh.login) source /etc/csh.login; if (-f ~/.login) so                                                                                                                                                                                 urce ~/.login; /bin/sh -c 'export -p' >! $xsess_tmp"
+    	. $xsess_tmp
+    	rm -f $xsess_tmp
+	;;
+	*/fish)
+    	. ${HOME}/.config/myshell/profile.sh
+		. ${HOME}/.config/myshell/bash/bprofile.sh
+    	xsess_tmp=$(mktemp /tmp/${HOME}/xsess-env-XXXXXX)
+    	$SHELL --login -c "/bin/sh -c 'export -p' > $xsess_tmp"
+    	. $xsess_tmp
+    	rm -f $xsess_tmp
+	;;
+	*) # Plain sh, ksh, and anything we do not know.
+    	. ${HOME}/.config/myshell/profile.sh
+		. ${HOME}/.config/myshell/bash/bprofile.sh
+	;;
 esac
