Update README.md

diff --git a/bin/bin/livewall b/bin/bin/livewall
--- a/bin/bin/livewall
+++ b/bin/bin/livewall
@@ -1,12 +1,10 @@
-#!/bin/bash
-shopt -s extglob
-
+#!/bin/sh
 _livewallpaper_dir="${HOME}/.local/livewallpaper"
 _dir_vid="${_livewallpaper_dir}/video"
 _autorun_livewall_file="${_livewallpaper_dir}/autorun"
 
 if [ "${1-}" = "-c" ] || [ "${1-}" = "--check-run-live" ];then
-	if [[ -f "${_autorun_livewall_file}" ]];then
+	if [ -f "${_autorun_livewall_file}" ];then
 		echo "true"
 	else
 		echo "false"
@@ -14,14 +12,7 @@ if [ "${1-}" = "-c" ] || [ "${1-}" = "--check-run-live" ];then
 	exit
 fi
 
-command -v ffmpeg >/dev/null 2>&1 || _ffmpeg_="I need ffmpeg: my-superuser apt install --no-install-recommends ffmpeg \n"
-command -v feh >/dev/null 2>&1 || _feh_="I need feh: my-superuser apt install --no-install-recommends feh \n"
-
-if [[ -n "${_feh_}" ]] || [[ -n "${_ffmpeg_}"  ]];then
-	echo "${_ffmpeg_}" 
-	echo "${_feh_}" 
-	exit 1
-fi
+check_4_dependencies_if_installed ffmpeg feh
 
 Use_numbers="Use numbers indicated by"
 Preparing_video="Preparing the video..."
@@ -31,7 +22,7 @@ mp4_only="MP4 format only"
 Report_Video="Report Video"
 no_videos="No videos."
 
-[[ ! -d "${_dir_vid}" ]] && mkdir -p "${_dir_vid}"
+[ ! -d "${_dir_vid}" ] && mkdir -p "${_dir_vid}"
 
 __help(){
   cat <<EOF
@@ -68,7 +59,7 @@ ctrl_c(){
 
 _quit_loop(){
     script_pid=$(pgrep -r "$0")
-    if [[ ! -z "$script_pid" ]];then
+    if [ -n "$script_pid" ];then
     	kill $script_pid 2>/dev/null >/dev/null
     fi
 }
@@ -79,22 +70,36 @@ _video(){
 		vid_dir_name="$(grep -R "$1" "${_dir_vid}" | awk -F'/video.info' '{print $1}')"
 		a="$(basename "${vid_dir_name}")"
 	else	
-		[[ -z "$1" ]] && { echo "${Report_Video}"; exit 1; }
-		[[ $(file -b --mime-type "${1}" | cut -d"/" -f1) != 'video' ]] && { echo "${Invalid_format}"; exit 1; }
-		[[ $(file -b --mime-type "${1}" | cut -d"/" -f2) != @(mp4|x-m4v) ]] && { echo "${mp4_only}"; exit 1; }
+		[ -z "$1" ] && { echo "${Report_Video}"; exit 1; }
+		mime_type=$(file -b --mime-type "$1" | cut -d"/" -f1)
+		if [ "$mime_type" != "video" ]; then
+    		echo "$Invalid_format"
+    		exit 1
+		fi
+		
+		extension=$(file -b --mime-type "$1" | cut -d"/" -f2)
+		case "$extension" in
+    		mp4|x-m4v)
+        		# Valid formats
+        		;;
+    		*)
+        		echo "$mp4_only"
+        		exit 1
+        		;;
+		esac
     	a=1     
     	for i in $(ls -d $_dir_vid/*/ 2>/dev/null); do
-       	if [[ -d "$_dir_vid/$a" ]]; then
-           	let a=a+1
+       	if [ -d "$_dir_vid/$a" ]; then
+           	a=$((a + 1))
        	fi
     	done
 	
     	mkdir -p "$_dir_vid/$a"
 	
-    	echo -e "${Preparing_video}...\r"
+    	printf "${Preparing_video}...\n"
     	ffmpeg -y -ss 00:00 -i ${1} -t 10 "${_dir_vid}/${a}/filename%05d.jpg" > ${_dir_vid}/${a}/video.info 2>&1
     	t=$(ls ${_dir_vid}/${a}/* | wc -l)
-    	let t=t-1
+    	t=$((t - 1))
     	echo ${1} > ${_dir_vid}/${a}/video.info
 	fi
 
@@ -103,14 +108,14 @@ _video(){
     while : ; do
         feh --bg-scale $(ls -1 ${_dir_vid}/${a}/* | sed -n "${i}p")
         sleep 0.01
-        let i=i+1
-        [[ "${i}" -gt "${t}" ]] && i=1              
+        i=$((i + 1))
+        [ "${i}" -gt "${t}" ] && i=1              
     done &
 }
 
 __autorun(){
-	if [[ -z "${1-}" ]];then
-		[[ -f "${_autorun_livewall_file}" ]] && rm -f "${_autorun_livewall_file}"
+	if [ -z "${1-}" ];then
+		[ -f "${_autorun_livewall_file}" ] && rm -f "${_autorun_livewall_file}"
 	else
 		if ! grep -q "$1" "${_autorun_livewall_file}";then
 			echo "${1-}" > "${_autorun_livewall_file}"
@@ -119,7 +124,7 @@ __autorun(){
 }
 
 __runit(){
-	if [[ -f "${_autorun_livewall_file}" ]];then
+	if [ -f "${_autorun_livewall_file}" ];then
 		video_name="$(cat "${_autorun_livewall_file}")"
 		_video "${video_name}"
 	fi
@@ -127,8 +132,8 @@ __runit(){
 
 _list_vid(){
     check_if_vid_exist_in_dir
-    __numbers_=($(cd ${_dir_vid} && ls))
-    for i in "${__numbers_[@]}"; do
+    __numbers_="$(cd ${_dir_vid} && ls)"
+    for i in ${__numbers_}; do
     	#videonumber → videoname
     	echo "${i} → $(cat ${_dir_vid}/${i}/video.info)"
     done
@@ -136,22 +141,22 @@ _list_vid(){
 
 _set_video(){
     check_if_vid_exist_in_dir
-    if [[ $(echo "$1" | sed -n -r '/^[0-9]+$/p') == "" ]]; then
+    if [ -z "$(echo "$1" | sed -n -r '/^[0-9]+$/p')" ]; then
         echo "${Use_numbers} '${0##*/} --list-videos'."
     else
-        if [[ "$1" -gt "$(ls -d1 "${_dir_vid}"/* | wc -l)" ]]; then
+        if [ "$1" -gt "$(ls -d1 "${_dir_vid}"/* | wc -l)" ]; then
             echo "${Use_numbers_from} $(ls -d1 ${_dir_vid}/* | wc -l)"
             exit 1
         else
             t=$(ls ${_dir_vid}/${1}/* | wc -l)
-            let t=t-1
+            t=$((t - 1))
             i=1
             # ctrl_c
             while : ; do
                 feh --bg-scale $(ls -1 ${_dir_vid}/${1}/* | sed -n "${i}p")
                 sleep 0.01
-                let i=i+1
-                [[ "${i}" -gt "${t}" ]] && i=1              
+                i=$((i + 1))
+                [ "${i}" -gt "${t}" ] && i=1              
             done &
         fi
     fi
diff --git a/bin/openbox/pipemenu/bl-tint2-pipemenu b/bin/openbox/pipemenu/bl-tint2-pipemenu
--- a/bin/openbox/pipemenu/bl-tint2-pipemenu
+++ b/bin/openbox/pipemenu/bl-tint2-pipemenu
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 #    bl-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
 #    This program is free software: you can redistribute it and/or modify
@@ -64,33 +64,46 @@ loadReload(){
     fi
 }
 
-loadEditSubmenu(){
-    local pid command TPATH TINT2
+loadEditSubmenu() {
     menuSubmenu "EditTint2" "Edit Tint2s"
-        if type style-manager >/dev/null 2>&1;then
-            menuItem "Tint2 Editor" "style-manager --tint2edit"
-        fi
-# tint2conf removed here but still available from "Applications" menu as Settings > Panel Manager
-#        menuItem "Tint2 Config GUI" "tint2conf"
-        menuItem "Default tint2rc" "my-text-editor '$TINT2DEFAULT'"
-        if pgrep -x -u "$USER" tint2 >/dev/null;then
-            menuSubmenu "RunningTint2" "Running Tint2s"
-            while read -r pid; do
-                mapfile -d '' -t command < "/proc/${pid}/cmdline" # use NULL delimiter to split cmdline into array 'command'
-                [[ ${command[0]} = 'tint2' ]]  || { echo "$0: pgrep parsing failed: command is not 'tint2'" >&2; continue;}
-                if (( ${#command[@]} > 1 )); then
-                    TPATH=${command[-1]} # tint2 takes no options other than -c, which is optional
-                    [[ $TPATH = /* ]] || TPATH="$HOME/$TPATH" # assume path is relative to $HOME
-                    TINT2=${TPATH#${TINT2PATH}/}
-                else
-                    TPATH="$TINT2DEFAULT"
-                    TINT2="Default tint2rc"
-                fi
-                [[ -f $TPATH ]] || { echo "$0: pgrep tint2 parsing failed: $TPATH is not a file" >&2; continue;}
-                menuItem "$TINT2" "my-text-editor ${TPATH@Q}"
-            done < <(pgrep -x 'tint2' -u "$USER")
-            menuSubmenuEnd
-        fi
+
+    if type style-manager >/dev/null 2>&1; then
+        menuItem "Tint2 Editor" "style-manager --tint2edit"
+    fi
+
+    menuItem "Default tint2rc" "my-text-editor '$TINT2DEFAULT'"
+
+    if pgrep -x -u "$USER" tint2 >/dev/null; then
+        menuSubmenu "RunningTint2" "Running Tint2s"
+        
+        pgrep -x -u "$USER" tint2 | while read -r pid; do
+            cmdline=""
+            while IFS= read -r part; do
+                cmdline="$cmdline $part"
+            done < "/proc/${pid}/cmdline"
+            set -- $cmdline
+            if [ "$1" != "tint2" ]; then
+                echo "$0: pgrep parsing failed: command is not 'tint2'" >&2
+                continue
+            fi
+            TPATH=""
+            set -- $cmdline
+            while [ "$1" ]; do
+                TPATH="$1"
+                shift
+            done
+            if [ "${TPATH#"/"}" = "$TPATH" ]; then
+                TPATH="$HOME/$TPATH"
+            fi
+            TINT2="${TPATH#${TINT2PATH}/}"
+            if [ ! -f "$TPATH" ]; then
+                echo "$0: pgrep tint2 parsing failed: $TPATH is not a file" >&2
+                continue
+            fi
+            menuItem "$TINT2" "my-text-editor $TPATH"
+        done
+        menuSubmenuEnd
+    fi
     menuSubmenuEnd
 }
 
@@ -101,7 +114,7 @@ checkHelpfile(){
     --filename=$HELPFILE --fontname=Monospace \
     --width=650 --height=700 \
     --button=OK:0"
-    if [[ -e $HELPFILE ]];then
+    if [ -e "$HELPFILE" ];then
         menuItem "Tint2 Manager Help" "$DLG"
     fi
 }
