Update README.md

diff --git a/bin/bin/virtual_machine b/bin/bin/virtual_machine
--- a/bin/bin/virtual_machine
+++ b/bin/bin/virtual_machine
@@ -11,99 +11,7 @@ elif command -v vmplayer &> /dev/null; then
 	exit
 fi
 
-cpu_are=""
-HVE=""
-virtualization_ready_file="/usr/share/my_stuff/system_files/virtualization_ready"
-
-yes_or_no(){
-	local MSG="${1-}"
-	read -r -p "${MSG} (yes/no) (default: yes)" yn
-	yn="${yn^^}"
-	[ "$yn" = "YES" ] && yn="Y"
-	[ "$yn" = "" ] && yn="Y"
-	[ "$yn" != "Y" ] && exit
-}
-
-check_IOMMU_support(){
-	echo "checking if IOMMU enabled"
-	if [ -e "/sys/kernel/iommu_groups/*" ] || [ -e "/sys/class/iommu/*" ] || $(cat /proc/cmdline | grep -q "iommu=on") || egrep -c '(vmx|svm)' /proc/cpuinfo;then
-		echo "IOMMU enabled"
-	else
-		echo "IOMMU Disabled"
-		yes_or_no "Do you want to IOMMU? (yes/no) (default: yes)"
-		enable_IOMMU_support
-	fi
-}
-
-enable_IOMMU_support(){
-	if [ "$cpu_are" = "intel" ];then
-		if ! grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | grep 'intel_iommu=on';then
-			if grep 'GRUB_CMDLINE_LINUX=""' /etc/default/grub;then
-				my-superuser sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="intel_iommu=on"/' /etc/default/grub
-			else
-				my-superuser sed -i 's/GRUB_CMDLINE_LINUX=\"\(.*\)\"/GRUB_CMDLINE_LINUX=\"\1 intel_iommu=on\"/' /etc/default/grub
-			fi
-		fi
-	fi
-					
-	if ! grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | grep 'iommu=pt';then
-		if grep 'GRUB_CMDLINE_LINUX=""' /etc/default/grub;then
-			my-superuser sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="iommu=pt"/' /etc/default/grub
-		else
-			my-superuser sed -i 's/GRUB_CMDLINE_LINUX=\"\(.*\)\"/GRUB_CMDLINE_LINUX=\"\1 iommu=pt\"/' /etc/default/grub
-		fi
-	fi
-	echo "grub edited to enable IOMMU."
-	my-superuser update-grub
-}
-
-check_if_host_ready_for_virt(){
-	echo 'checking  if host is ready for virtualization .....'
-	cpu_type=$(lscpu | grep "Vendor ID:")
-	if echo "$cpu_type" | grep -iq intel;then
-		cpu_are=intel
-		HVE="VT-x"
-	elif echo "$cpu_type" | grep -iq amd;then
-		cpu_are=amd
-		HVE="AMD-V"
-	fi
-
-	if ! lscpu | grep Virtualization | grep -q "$HVE";then
-		echo "hardware virtualization extension is most likely disabled in the BIOS/UEFI. enable it."
-		failed_
-	fi
-	
-	if [ -n "$(zgrep CONFIG_KVM /boot/config-$(uname -r) | grep -vE "^#|=y|=m")" ];then
-		echo "krenal doest not support virtualization"
-		failed_
-	fi
-	check_IOMMU_support
-	my-superuser touch "${virtualization_ready_file}"
-	echo 'system is read for virtualization.'
-	echo "REBOOT MIGHT BE REQUIRED IF THE VM DOES NOT BOOT PROPERLY."
-}
-
-Reload_KVM_Kernel_Modules(){
-	echo "FUNCTION: Reload KVM Kernel Modules"
-	if [[ $cpu_are == "amd" ]]; then
-    	sudo modprobe -r kvm_amd kvm
-    	sudo modprobe kvm 
-    	sudo modprobe kvm_amd nested=1 
-	elif [[ $cpubrand == "intel" ]]; then
-  		my-superuser modprobe -r kvm_intel kvm
-    	my-superuser modprobe kvm
-    	my-superuser modprobe kvm_intel nested=1
-	fi
-	echo -e "Modprobe finished"
-}
-
-failed_(){
-	echo ' --- Installtion Failed --- ' 
-	read -p '  Press any key to exit'
-	exit
-}  
-
-[ ! -f "${virtualization_ready_file}" ] && check_if_host_ready_for_virt
+my-installer --tweek "Enable_IOMMU_support" || (echo "Failed to enable IOMMU Support." && exit 1)
 
 echo 'Do you want to install VirtualBox or Virt-manager?'
 echo '[1 or m] for Virt-manager'
@@ -124,5 +32,4 @@ else
     exit 1
 fi
 clear 
-Reload_KVM_Kernel_Modules
 echo ' --- Installtion Complated --- ' && read -p '  Press any key to exit'
