Update style_picker

diff --git a/bin/X11/yad/style_picker b/bin/X11/yad/style_picker
--- a/bin/X11/yad/style_picker
+++ b/bin/X11/yad/style_picker
@@ -322,139 +322,135 @@ Intro(){
 		2>/dev/null
 }
 	
-Launch_YAD_(){
-	CONFIGDIR=""
-	
-	getSet(){
-		. "${Distro_config_file}"
-    	SET="$Style_name"
-	}
-	
-	restoreSettings(){
-    	getSet          # get name of latest set BLOB config
-    	DLGLIST=""
-    	setARR=()
-    	namesARR=()
-    	thumbsARR=()
-    	i=0
-    	for dir in "$GLOBALCONFIGPATH"/* "$CONFIGPATH"/* ;do
-        	if [[ -d "$dir" ]];then
-            	d=$(echo $dir | sed -e 's/ /_/g')    # replace any spaces in dir name
-            	namesARR[$i]="<big>$(basename $d)</big>" # add theme collection name to array
-            	d=${d##*/}  # get directory name
-            	# Get name of current session, set icon for TRUE/FALSE
-            	if [[ "$SET" = "$d" ]];then
-                	setARR[$i]="gtk-yes"
-            	else
-                	setARR[$i]="gtk-no"
-            	fi
-            	IMGTHUMB="Brak"     # Placeholder if no thumbnail found
-            	f="$dir"/*"-thumb.jpg"
-            	if [[ "$f" ]];then
-                	IMGTHUMB="$f"
-            	fi
-            	thumbsARR[$i]="$IMGTHUMB"
-            	i=$(($i+1))
-        	fi
-    	done
-    	for ((j=0; j<${#namesARR[*]}; j++));do
-        	DLGLIST="$DLGLIST ${setARR[j]} ${namesARR[j]} ${thumbsARR[j]}"
-    	done
-    	FPATH=""
-    	while true ;do
-        	CONFIG=$($DIALOGDEC --list --title="$TITLE" --image=preferences-desktop-theme\
-            	--text="$MAIN_TEXT" \
-            	--separator=" " \
-            	--button="$ABOUT" \
-            	--button="$VIEW_IMG" --button="$ADD" \
-            	--button="$DELETE" --button=$RESTORE $EXIT \
-            	--always-print-result \
-            	--width=$W --height=$H --center --image-preview \
-            	--expand-column=3 \
-            	--column="$ACTIVE":IMG \
-            	--column="$NAME":TEXT \
-            	--column="$SCREEN_SHOT":IMG \
-            	$DLGLIST \
-            	2>/dev/null )
-        	RET=$?
-        	if [[ "$CONFIG" ]];then
-            	Style=$(echo "$CONFIG" | awk -F'[>|<]' '{print $3}' )
-            	if [ -d "$CONFIGPATH/$Style" ];then
-            		FPATH="$CONFIGPATH/$Style"
-            	else
-            		FPATH="$GLOBALCONFIGPATH/$Style"
-            	fi
-        	fi
-        	case $RET in
-            	0)  # RESTORE
-                	CURSESSION="$(basename $FPATH)"
-                	break
-                	;;
-            	1)  # EXIT
-            		exit 0
-                	;;
-            	2)  # DELETE
-            		if [[ ! "$CONFIG" ]];then
-                    	$DIALOG --text="$CHOOSE_BEFORE_DELETE" "$EXIT" "$OK" 2>/dev/null
-                    	if [ "$?" -eq 0 ];then
-                        	continue
-                    	else
-                        	exit 0
-                    	fi
-                	fi
-                	TEXT="$DELETE_FOR_SURE"
-                	if $DIALOG "$T$TEXT" "$CANCEL" "$OK" 2>/dev/null;then
-                    	[ -f "$FPATH" ] && rm -rf "$FPATH"
-                    	[ -f "$FPATH.jpg" ] && rm "$FPATH.jpg"
-                    	echo -e "\n$Style DELETED"
-                    	currentsession="$CURSESSION"
-                    	fpath=$(basename $FPATH)
-                    	if [[ $currentsession = $fpath ]];then
-                        	CURSESSION=""
-                    	fi
-                    	restoreSettings
-                	else
-                    	continue
-                	fi
-                	;;
-            	3)  #ADD
-                	saveStyle
-                	restoreSettings
-                	;;
-            	4)  # show screenshot in image viewer
-                	getSet
-                	if [ -f "$CONFIGPATH/${SEL}.jpg" ];then
-            			my-image-viewer "$CONFIGPATH/${SEL}.jpg"
-            		else
-            			my-image-viewer "$GLOBALCONFIGPATH/${SEL}.jpg" || echo "failed to locate: $GLOBALCONFIGPATH/${SEL}.jpg"
-            		fi
-                	restoreSettings
-                	;;
-            	5)  # ABOUT
-            		Intro
-                	;;
-            	*)  exit ;;
-        	esac
-    	done
-		"${__distro_path_root}"/bin/X11/WM/style_changer "$_panel_name_" "$CURSESSION"
-		#if . "$FPATH/lightdm-gtk-greeter.conf";then
-    	#	apps_as_root "${__distro_path_root}/bin/not_add_2_path/setLightdmGreeter" "$greeter_background" "$greeter_theme_name" "$greeter_icon_theme_name" "$greeter_font_name" "$greeter_position" \
-    	#		|| rofi -e "\n  LightdmGreeter File Restored. \n" -theme "$HOME/.config/rofi/$ROFI_STYLE"/massage.rasi
-    	#fi
-    	restoreSettings   
-	}
-	# set yad H and W
-    PRIMARY=$(xrandr -q | awk '/ connected/ {if ($3=="primary") print $4; else print $3}')
-    PSIZE=${PRIMARY%%x*}    # Primary monitor width
-    desktopW=$(xrandr -q | awk '/Screen/ {print $8}')  # total desktop width
-    desktopH=$(xrandr -q | awk '/Screen/ {print $10}') # desktop height
-    desktopH=${desktopH%%,*}    # remove trailing comma
-    W=$(( $PSIZE / 3 ))  # 1/3 width primary monitor
-    H=$(( ($desktopH / 3)*2 ))  # 2/3 height
-    
-	getSet
-	restoreSettings
-	exit 0
-}
+CONFIGDIR=""
 
-Launch_YAD_
+getSet(){
+	. "${Distro_config_file}"
+   	SET="$Style_name"
+}
+	
+restoreSettings(){
+   	getSet          # get name of latest set BLOB config
+   	DLGLIST=""
+   	setARR=()
+   	namesARR=()
+   	thumbsARR=()
+   	i=0
+   	for dir in "$GLOBALCONFIGPATH"/* "$CONFIGPATH"/* ;do
+       	if [[ -d "$dir" ]];then
+           	d=$(echo $dir | sed -e 's/ /_/g')    # replace any spaces in dir name
+           	namesARR[$i]="<big>$(basename $d)</big>" # add theme collection name to array
+           	d=${d##*/}  # get directory name
+           	# Get name of current session, set icon for TRUE/FALSE
+           	if [[ "$SET" = "$d" ]];then
+               	setARR[$i]="gtk-yes"
+           	else
+               	setARR[$i]="gtk-no"
+           	fi
+           	IMGTHUMB="Brak"     # Placeholder if no thumbnail found
+           	f="$dir"/*"-thumb.jpg"
+           	if [[ "$f" ]];then
+               	IMGTHUMB="$f"
+           	fi
+           	thumbsARR[$i]="$IMGTHUMB"
+           	i=$(($i+1))
+       	fi
+   	done
+   	for ((j=0; j<${#namesARR[*]}; j++));do
+       	DLGLIST="$DLGLIST ${setARR[j]} ${namesARR[j]} ${thumbsARR[j]}"
+   	done
+   	FPATH=""
+   	while true ;do
+       	CONFIG=$($DIALOGDEC --list --title="$TITLE" --image=preferences-desktop-theme\
+           	--text="$MAIN_TEXT" \
+           	--separator=" " \
+           	--button="$ABOUT" \
+           	--button="$VIEW_IMG" --button="$ADD" \
+           	--button="$DELETE" --button=$RESTORE $EXIT \
+           	--always-print-result \
+           	--width=$W --height=$H --center --image-preview \
+           	--expand-column=3 \
+           	--column="$ACTIVE":IMG \
+           	--column="$NAME":TEXT \
+           	--column="$SCREEN_SHOT":IMG \
+           	$DLGLIST \
+           	2>/dev/null )
+       	RET=$?
+       	if [[ "$CONFIG" ]];then
+           	Style=$(echo "$CONFIG" | awk -F'[>|<]' '{print $3}' )
+           	if [ -d "$CONFIGPATH/$Style" ];then
+           		FPATH="$CONFIGPATH/$Style"
+           	else
+           		FPATH="$GLOBALCONFIGPATH/$Style"
+           	fi
+       	fi
+       	case $RET in
+           	0)  # RESTORE
+               	CURSESSION="$(basename $FPATH)"
+               	break
+               	;;
+           	1)  # EXIT
+           		exit 0
+               	;;
+           	2)  # DELETE
+           		if [[ ! "$CONFIG" ]];then
+                   	$DIALOG --text="$CHOOSE_BEFORE_DELETE" "$EXIT" "$OK" 2>/dev/null
+                   	if [ "$?" -eq 0 ];then
+                       	continue
+                   	else
+                       	exit 0
+                   	fi
+               	fi
+               	TEXT="$DELETE_FOR_SURE"
+               	if $DIALOG "$T$TEXT" "$CANCEL" "$OK" 2>/dev/null;then
+                   	[ -f "$FPATH" ] && rm -rf "$FPATH"
+                   	[ -f "$FPATH.jpg" ] && rm "$FPATH.jpg"
+                   	echo -e "\n$Style DELETED"
+                   	currentsession="$CURSESSION"
+                   	fpath=$(basename $FPATH)
+                   	if [[ $currentsession = $fpath ]];then
+                       	CURSESSION=""
+                   	fi
+                   	restoreSettings
+               	else
+                   	continue
+               	fi
+               	;;
+           	3)  #ADD
+               	saveStyle
+               	restoreSettings
+               	;;
+           	4)  # show screenshot in image viewer
+               	getSet
+               	if [ -f "$CONFIGPATH/${SEL}.jpg" ];then
+           			my-image-viewer "$CONFIGPATH/${SEL}.jpg"
+           		else
+           			my-image-viewer "$GLOBALCONFIGPATH/${SEL}.jpg" || echo "failed to locate: $GLOBALCONFIGPATH/${SEL}.jpg"
+           		fi
+               	restoreSettings
+               	;;
+           	5)  # ABOUT
+           		Intro
+               	;;
+           	*)  exit ;;
+       	esac
+   	done
+	"${__distro_path_root}"/bin/X11/WM/style_changer "$_panel_name_" "$CURSESSION"
+	#if . "$FPATH/lightdm-gtk-greeter.conf";then
+   	#	apps_as_root "${__distro_path_root}/bin/not_add_2_path/setLightdmGreeter" "$greeter_background" "$greeter_theme_name" "$greeter_icon_theme_name" "$greeter_font_name" "$greeter_position" \
+   	#		|| rofi -e "\n  LightdmGreeter File Restored. \n" -theme "$HOME/.config/rofi/$ROFI_STYLE"/massage.rasi
+   	#fi
+   	restoreSettings   
+}
+# set yad H and W
+PRIMARY=$(xrandr -q | awk '/ connected/ {if ($3=="primary") print $4; else print $3}')
+PSIZE=${PRIMARY%%x*}    # Primary monitor width
+desktopW=$(xrandr -q | awk '/Screen/ {print $8}')  # total desktop width
+desktopH=$(xrandr -q | awk '/Screen/ {print $10}') # desktop height
+desktopH=${desktopH%%,*}    # remove trailing comma
+W=$(( $PSIZE / 3 ))  # 1/3 width primary monitor
+H=$(( ($desktopH / 3)*2 ))  # 2/3 height
+
+getSet
+restoreSettings
+exit 0
