Update README.md

diff --git a/bin/X11/yad/uploader/upload-imgbb b/bin/X11/yad/uploader/upload-imgbb
--- a/bin/X11/yad/uploader/upload-imgbb
+++ b/bin/X11/yad/uploader/upload-imgbb
@@ -27,6 +27,7 @@
 #
 ########################################################################
 
+. "/usr/share/my_stuff/lib/common/Distro_path"
 check_4_dependencies_if_installed yad jq xdotool convert || exit 1
 
 export API_URL="https://api.imgbb.com/"   # used by run_browser()
@@ -90,7 +91,7 @@ done
 CLIENT_API_KEY="$(myAPIman show imgbb || :)"
 
 #### YAD ###
-DIALOG="yad --center --borders=20 --window-icon=/usr/share/my_stuff/Distro_Specific/icons/linux.svg"
+DIALOG="yad --center --borders=20 --window-icon=${__distro_path_root}/Distro_Specific/icons/linux.svg"
 TITLE="--title=Image BBCode"
 T="--text="
 DELETE="--button=Delete:2"
@@ -220,7 +221,7 @@ function make_thumbnail(){
 
 function delete_local(){    # delete local screenshot; don't delete if '--file' was script arg.
     local message msg ret
-    source "/usr/share/my_stuff/lib/common/yad-includes"
+    source "${__distro_path_root}/lib/common/yad-includes"
 
     if (( F_FLAG == 0));then    # local file wasn't uploaded, so don't offer to delete it
         message="\n\tMove local screenshot image to 'Trash'?\n\n\t${img_file}\n"
@@ -539,8 +540,8 @@ function main(){
 
     [[ -z "${IMG_VIEWER}" ]] && IMG_VIEWER="my-www-browser"
 
-    if ! . "/usr/share/my_stuff/lib/common/yad-includes" 2> /dev/null;then
-        echo "Error: Failed to source yad-includes in /usr/share/my_stuff/lib/common" >&2
+    if ! . "${__distro_path_root}/lib/common/yad-includes" 2> /dev/null;then
+        echo "Error: Failed to source yad-includes in ${__distro_path_root}/lib/common" >&2
         exit 1
     elif ! . "${SETTINGS_FILE}" 2> /dev/null;then
         echo "Error: Failed to source ${SETTINGS_FILE} in ${USR_CFG_DIR}/" >&2
diff --git a/bin/X11/yad/uploader/upload-imgur b/bin/X11/yad/uploader/upload-imgur
--- a/bin/X11/yad/uploader/upload-imgur
+++ b/bin/X11/yad/uploader/upload-imgur
@@ -20,6 +20,7 @@
 #
 ########################################################################
 
+. "/usr/share/my_stuff/lib/common/Distro_path"
 check_4_dependencies_if_installed yad jq xprop wmctrl xdotool || exit 1
 
 USR_CFG_DIR="$HOME/.config/image-upload/imgur"
@@ -743,7 +744,7 @@ function switch_to_browser(){   # switch to new browser tab
 ######## End OAuth Functions ###########################################
 
 ######## YAD ###########################################################
-DIALOG="yad --center --borders=20 --window-icon=/usr/share/my_stuff/Distro_Specific/icons/linux.svg --fixed"
+DIALOG="yad --center --borders=20 --window-icon=${__distro_path_root}/Distro_Specific/icons/linux.svg --fixed"
 TITLE="--title=Image BBCode"
 T="--text="
 DELETE="--button=Delete:2"
@@ -769,8 +770,8 @@ TEST=0                      # Flag to test if user has Imgur account
 export -f run_browser       # to be used as YAD button command
 export -f switch_to_browser # used by run_browser
 
-if ! . "/usr/share/my_stuff/lib/common/yad-includes" 2> /dev/null;then
-    echo -e "\nError: Failed to source yad-includes in /usr/share/my_stuff/lib/common" >&2
+if ! . "${__distro_path_root}/lib/common/yad-includes" 2> /dev/null;then
+    echo -e "\nError: Failed to source yad-includes in ${__distro_path_root}/lib/common" >&2
     exit 1
 elif ! . "${SETTINGS_FILE}" 2> /dev/null;then
     echo -e "\nError: Failed to source ${SETTINGS_FILE} in ${USR_CFG_DIR}/" >&2
diff --git a/distro_manager/distro-uninstaller b/distro_manager/distro-uninstaller
--- a/distro_manager/distro-uninstaller
+++ b/distro_manager/distro-uninstaller
@@ -1,22 +1,23 @@
 #!/bin/sh
 is_it_zero_byte=false
 
-. "/usr/share/my_stuff/never_remove/var_for_distro_uninstaller"
-. "/usr/share/my_stuff/lib/common/common"
-. "/usr/share/my_stuff/Distro_Specific/Package-manager.sh"
-. "/usr/share/my_stuff/lib/common/my_installer_and_DB_dir"
+. "/usr/share/my_stuff/lib/common/Distro_path"
+. "${__distro_path_root}/never_remove/var_for_distro_uninstaller"
+. "${__distro_path_root}/lib/common/common"
+. "${__distro_path_root}/Distro_Specific/Package-manager.sh"
+. "${__distro_path_root}/lib/common/my_installer_and_DB_dir"
 
 for backup in icons themes fonts;do
 	my-superuser find /usr/share/${backup} -depth -maxdepth 1 -type l -delete
-	my-superuser mv /usr/share/my_stuff/system_files/backup/${backup} /usr/share/${backup}
+	my-superuser mv ${__distro_path_root}/system_files/backup/${backup} /usr/share/${backup}
 done
 
 if ls "$CHROOT_SCRIPT_PATH"/chroot-* >/dev/null 2>&1;then
 	my-superuser rm -rdf "$CHROOT_SCRIPT_PATH"/chroot-*
 fi
 
-if grep -q "$CHROOT_SCRIPT_PATH/chroot-" /usr/share/my_stuff/system_files/doas.conf 2>&1;then
-	my-superuser sed -i "|$CHROOT_SCRIPT_PATH/chroot-|d" /usr/share/my_stuff/system_files/doas.conf
+if grep -q "$CHROOT_SCRIPT_PATH/chroot-" ${__distro_path_root}/system_files/doas.conf 2>&1;then
+	my-superuser sed -i "|$CHROOT_SCRIPT_PATH/chroot-|d" ${__distro_path_root}/system_files/doas.conf
 	my-superuser sed -i "|$CHROOT_SCRIPT_PATH/chroot-|d" /etc/doas.conf
 fi
 
@@ -89,11 +90,11 @@ echo "updating gtk-update"
 my-superuser gtk-update-icon-cache > /dev/null 2>&1
 echo "updating grub"
 grub_updater_function
-echo "removing /usr/share/my_stuff"
-my-superuser rm -rdf "/usr/share/my_stuff"
+echo "removing ${__distro_path_root}"
+my-superuser rm -rdf "${__distro_path_root}"
 
 echo "running myautorandr.sh"
-my-superuser /usr/share/my_stuff/bin/X11/not_add_2_path/myautorandr.sh uninstall || echo "failed to run myautorandr.sh uninstaller"
+my-superuser ${__distro_path_root}/bin/X11/not_add_2_path/myautorandr.sh uninstall || echo "failed to run myautorandr.sh uninstaller"
 
 echo "delete /usr/bin/my-superuser"
 my-superuser rm -rdf /usr/bin/my-superuser || :
